### ISSUE TITLE
 no module named 'plugin'

### ISSUE THREAD

**Issue by Zhangjyhhh** [myc634/UltraLiDAR_nusc_waymo#2]
hello! in eval step 0, i met issue:
```shell
(ultralidar) jyzhang@sumig-System-Product-Name:~/mmdetection3d/UltraLiDAR_nusc_waymo$ python -m torch.distributed.launch --nproc_per_node=1 --master_port=29501 ./tools/test.py ./configs/ultralidar_nusc_static_blank_code.py  --eval "mIoU"
/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "./tools/test.py", line 15, in <module>
    from plugin.datasets.builder import build_dataloader
ModuleNotFoundError: No module named 'plugin'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3771) of binary: /home/jyzhang/anaconda3/envs/ultralidar/bin/python
Traceback (most recent call last):
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-25_16:10:43
  host      : sumig-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3771)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by myc634** [comment]
please try https://github.com/myc634/UltraLiDAR_nusc_waymo/blob/6337c2440dee9489df825ecc5a5b9a01cff2c094/tools/mmdet_train.py#L13 instead and see whether this can solve your problem

**Comment by Zhangjyhhh** [comment]
> please try
> 
> https://github.com/myc634/UltraLiDAR_nusc_waymo/blob/6337c2440dee9489df825ecc5a5b9a01cff2c094/tools/mmdet_train.py#L13
> instead and see whether this can solve your problem

yeah, it does help, but another issue occured:
```shell
(ultralidar) jyzhang@sumig-System-Product-Name:~/mmdetection3d/UltraLiDAR_nusc_waymo$ python -m torch.distributed.launch --nproc_per_node=1 --master_port=29501 ./tools/test.py ./configs/ultralidar_nusc_static_blank_code.py ./configs/epoch_80.pth --launcher pytorch --eval mIoU
/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
plugin
work_dir:  /media/jyzhang/C0FED904FED8F39E/wok_dir_zjy/nusc_stage2
Traceback (most recent call last):
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() missing 1 required positional argument: 'classes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test.py", line 277, in <module>
    main()
  File "./tools/test.py", line 208, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: NuscDataset: __init__() missing 1 required positional argument: 'classes'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15983) of binary: /home/jyzhang/anaconda3/envs/ultralidar/bin/python
Traceback (most recent call last):
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jyzhang/anaconda3/envs/ultralidar/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-27_12:00:03
  host      : sumig-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15983)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```
