### ISSUE TITLE
KeyError: 'UltraLiDAR is not in the models registry'

### ISSUE THREAD

**Issue by Lu034** [myc634/UltraLiDAR_nusc_waymo#9]
Hi! in Stage 1 training, and i met following error:

Traceback (most recent call last):
  File "tools/train.py", line 278, in <module>
    main()
  File "tools/train.py", line 218, in main
    model = build_model(
  File "c:\users\user\desktop\lidar\mmdetection3d\mmdet3d\models\builder.py", line 86, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "c:\users\user\desktop\lidar\mmdetection3d\mmdet3d\models\builder.py", line 59, in build_detector
    return DETECTORS.build(
  File "C:\Users\USER\anaconda3\envs\ultralidar\lib\site-packages\mmcv\utils\registry.py", line 215, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\Users\USER\anaconda3\envs\ultralidar\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\USER\anaconda3\envs\ultralidar\lib\site-packages\mmcv\utils\registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'UltraLiDAR is not in the models registry'

i don't how to solve this problem, could you help me?

**Comment by myc634** [comment]
please refer to [https://github.com/myc634/UltraLiDAR_nusc_waymo/issues/1](url)
